# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('completed', models.BooleanField()),
                ('finished_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomodoro.Task'),
        ),
    ]
