# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_auto_20170406_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('pomodoro_duration', models.IntegerField(default=25)),
                ('short_break', models.IntegerField(default=5)),
                ('long_break', models.IntegerField(default=30)),
                ('long_break_after', models.IntegerField(default=4)),
                ('daily_target', models.IntegerField(default=14)),
            ],
        ),
    ]
